M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-06-15T18:42:43-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-15T18:42:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X146.34Y-94.2
X146.34Y-99.98
T2
X143.0Y-83.0
X143.0Y-112.0
X167.0Y-83.0
X167.0Y-112.0
M30
